apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: exampleservice
    newTag: dev

configMapGenerator:
  - name: exampleservice
    envs:
      - .env
